In [4]:
import torch
src = torch.arange(1, 11).reshape(2, 5)
print(src)

index = torch.tensor([[0, 1, 2, 0]])
# 测试scatter函数
# scatter：将src中的值写入当前张量的index数组指定下标中。除了dim由index决定外，其余部分由src决定。
# 即如果dim=0, res[index[i][j], j] = src[i, j]
# 这里(0, 0)=src[0,0] (1, 1)=src[0, 1] (2, 2)=src[0, 2], (0, 3)=src[0, 3]
res = torch.zeros(3, 5, dtype=src.dtype).scatter_(dim=0, index=index, src=src)
print(res)

# 如果dim=1, res[i, index[i][j]] = src[i, j]
index = torch.tensor([[0, 1, 2], [0, 1, 4]])
res = torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src)
print(res)

output = torch.tensor([[0, 0 ,1], [0, 1, 0]])
pred = torch.tensor([[2], [1]])
print(pred.view(-1, 1))
res = torch.zeros(output.size()).scatter_(1, pred.view(-1, 1), 1.)
print(res)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])
tensor([[1, 2, 3, 0, 0],
        [6, 7, 0, 0, 8],
        [0, 0, 0, 0, 0]])
tensor([[2],
        [1]])
tensor([[0., 0., 1.],
        [0., 1., 0.]])
